### ISSUE TITLE
`블레이즈 어웨이(BlazeAway)`로 공격 대상이 없을 때 공격하려 할 시 Crash 발생함

### ISSUE THREAD

**Issue by tykr0001** [scarf005/Marisa#133]
### How to reproduce

1. 마리사로 새 게임 시작
2. 콘솔에 `fight Awakened_One` 입력
3. 단순한 스파크 등 아무 단일 공격카드로 작은 까까 잡고 콘솔에 `kill all`
4. 콘솔에 `hand add BlazeAway` 입력 후 사용
5. Crash 발생

### Crash log

```
Game crashed.
Version Info:
 - Java version (1.8.0_144)
 - Slay the Spire (12-18-2022)
 - ModTheSpire (3.30.3)
Mod list:
 - versiontwocompatible (2.2.5)
 - basemod (5.50.0)
 - AchievementEnabler (1.0.0)
 - Better_Animation (0.2.0)
 - DeckTracker (0.1.13)
 - test447_keycuts (1.0)
 - RelicStats (1.2.2)
 - stslib (2.7.1)
 - superfastmode (1.0.8)
 - MarisaContinued (1.7.0)

Mods in stacktrace:
 - MarisaContinued (1.7.0)
Cause:
java.lang.NullPointerException
	at marisa.action.BlazeAwayAction.update(BlazeAwayAction.kt:36)
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:179)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:325)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2532)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:876)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

**Comment by scarf005** [comment]
버그 재현함
마지막 사용한 공격 카드의 대상이 이미 죽어있으니 `null`인데 `null`인 대상을 상대로 공격을 시도해서 터지는 것으로 보임
수정 진행하겠음
