### ISSUE TITLE
Selection Screen Duplicates + Duplicate Card Library Tabs

### ISSUE THREAD

**Issue by NE0SPACE** [scarf005/Marisa#140]
### How to reproduce

1. Launch Game
2. Go to the Compendium
3. Go to the Card Library
4. There are duplicate "Marisa" and "Marisa_derivations" tabs. Clicking the wrong ones will crash the game.

Additionally, when on the character select screen there are 2 selection slots present for Marisa. Selecting either of these seem to start a new game with Marisa just fine, but I am still mentioning it here just in case.

### Crash log

Version Info:
 - Java version (1.8.0_144)
 - Slay the Spire (12-18-2022)
 - ModTheSpire (3.30.3)
Mod list:
 - basemod (5.51.1)
 - stslib (2.8.0)
 - permNeow (1)
 - downfall (4.2.08)
 - TS05_Marisa (0.15.4)
 - MarisaContinued (2.0.0)
 - BlackRuseMod (0.9.4)
 - PatchouliMod (1.1.4)
 - anniv5 (1.4.1)
 - YakuzaMod (1.1.1)

Cause:
java.lang.NullPointerException
	at com.megacrit.cardcrawl.screens.compendium.CardLibSortHeader.setGroup(CardLibSortHeader.java:60)
	at com.megacrit.cardcrawl.screens.compendium.CardLibraryScreen.didChangeTab(CardLibraryScreen.java:533)
	at basemod.patches.com.megacrit.cardcrawl.screens.mainMenu.ColorTabBar.ColorTabBarFix$Update.Postfix(ColorTabBarFix.java:107)
	at com.megacrit.cardcrawl.screens.mainMenu.ColorTabBar.update(ColorTabBar.java:133)
	at com.megacrit.cardcrawl.screens.compendium.CardLibraryScreen.update(CardLibraryScreen.java:163)
	at com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen.update(MainMenuScreen.java:216)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:789)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by scarf005** [comment]
could you please try disabling old mod (TS05_Marisa) then try again? judging by the log, you've enabled both [Marisa: Continued](https://steamcommunity.com/sharedfiles/filedetails/?id=2902980404) and original [Marisa](https://steamcommunity.com/sharedfiles/filedetails/?id=1614104912) mod.

> This mod cannot be played with original mod.

since both mod share almost identical ids, using both may cause collision and crash the game.

**Comment by NE0SPACE** [comment]
> could you please try disabling old mod (TS05_Marisa) then try again? judging by the log, you've enabled both [Marisa: Continued](https://steamcommunity.com/sharedfiles/filedetails/?id=2902980404) and original [Marisa](https://steamcommunity.com/sharedfiles/filedetails/?id=1614104912) mod.
> 
> > This mod cannot be played with original mod.
> 
> since both mod share almost identical ids, using both may cause collision and crash the game.
> 

Ah, yeah. That seems to have been the problem.

I thought it had said that the mod cannot be played without the original mod, for some reason.

Sorry.

**Comment by scarf005** [comment]
no worries, i'll try changing the description to be more explicit.
