### ISSUE TITLE
When I try to start the game in Japanese, it crashes

### ISSUE THREAD

**Issue by ackeyGAME** [scarf005/Marisa#141]
### How to reproduce

1,Set the game language setting to Japanese and exit
2,Install and launch marisamod

The game does not start and crashes.

### Crash log

Version Info:
- java version (1.8.0_341)
- Slay the Spire (12-18-2022)
- ModTheSpire (3.30.3)
Mod list:
- basemod (5.51.1)
- MarisaContinued (2.0.0)
Cause:
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.ExceptionInInitializerError
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.ExceptionInInitializerError
	at marisa.MarisaContinued.cardsToAdd(MarisaContinued.kt:198)
	at marisa.MarisaContinued.access$cardsToAdd(MarisaContinued.kt:44)
	at marisa.MarisaContinued$receiveEditCards$1.invoke(MarisaContinued.kt:96)
	at marisa.MarisaContinued$receiveEditCards$1.invoke(MarisaContinued.kt:95)
	at marisa.LoggingKt.runInfo(Logging.kt:8)
	at marisa.MarisaContinued.receiveEditCards(MarisaContinued.kt:95)
	at basemod.BaseMod.publishEditCards(BaseMod.java:2519)
	at basemod.patches.com.megacrit.cardcrawl.helpers.CardLibrary.EditCardsPatch.Prefix(EditCardsPatch.java:11)
	at com.megacrit.cardcrawl.helpers.CardLibrary.initialize(CardLibrary.java)
	at com.megacrit.cardcrawl.core.CardCrawlGame.create(CardCrawlGame.java:282)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: java.lang.NullPointerException: cardStrings.EXTENDED_DESCRIPTION must not be null
	at marisa.cards.GravityBeat.<clinit>(GravityBeat.kt:72)
	... 12 more

**Comment by ackeyGAME** [comment]
I only speak Japanese, so I use the translation tool DeepL
