### ISSUE TITLE
exception when playing unstable bomb

### ISSUE THREAD

**Issue by allaryin** [scarf005/Marisa#202]
### How to reproduce

1. play unstable bomb
2. crash some times

I believe this might only be happening when there is only one enemy in the fight? I just played through act 1, and almost (but not quite) every time I played `Unstable Bomb`, there was a crash with the same exception.

Don't feel like reading Kotlin right now, but I'm guessing this is just a bad bounds check (num enemies - 1) sort of deal.

### Crash log

Version Info:
 - Java version (1.8.0_144)
 - Slay the Spire (12-18-2022)
 - ModTheSpire (3.30.3)
Mod list:
 - basemod (5.52.2)
 - AchievementEnabler (1.0.0)
 - mintyspire (2.5.5)
 - RelicStats (1.2.2)
 - stslib (2.9.0)
 - ReplayTheSpireMod (1.6.7)
 - anniv5 (1.7.0)
 - spireTogether (4.2.0)
 - ojb_Bestiary (0.1.1)
 - coloredmap (2.4.1)
 - coloredpowertips (2.3.0)
 - DeckTracker (0.1.13)
 - HighlightPath (0.0.3)
 - MarisaContinued (3.1.0)
 - beeyee_MasteryChallenge (0.0.1)
 - RunHistoryPlus (1.8.0)

Mods in stacktrace:
 - MarisaContinued (3.1.0)
Cause:
java.lang.IllegalArgumentException: n must be positive
	at com.badlogic.gdx.math.RandomXS128.nextLong(RandomXS128.java:110)
	at com.badlogic.gdx.math.RandomXS128.nextInt(RandomXS128.java:99)
	at com.megacrit.cardcrawl.random.Random.random(Random.java:71)
	at marisa.action.UnstableBombAction.<init>(UnstableBombAction.kt:23)
	at marisa.cards.UnstableBomb.use(UnstableBomb.kt:33)
	at com.megacrit.cardcrawl.characters.AbstractPlayer.useCard(AbstractPlayer.java:1698)
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:359)
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:175)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:325)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2532)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:876)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by scarf005** [comment]
i wasn't able to reproduce it, could you provide exact console command instructions to reproduce the issue reliably?
in the video i fight two enemies and a single enemy, yet it does not crashes.

https://user-images.githubusercontent.com/54838975/233778034-d21c2fd8-d822-4316-91c3-49038ef88641.mp4

**Comment by HeJuiczehn** [comment]
just encountered the same bug with same crash log. 
when use "upgarde!" 2 times, and then "unstable bomb" will cause random damage (5 to 4) 4 times,  and the game definitely crash if use this card. 
maybe random number generator requires the first number not bigger than the latter one or something.

**Comment by scarf005** [comment]
thank you. i was able to reproduce the issue, and it was indeed a random range issue. i'm currently working on a bugfix for it.
