### ISSUE TITLE
namespace clash in `ChargeUpPower`

### ISSUE THREAD

**Issue by URARUA** [scarf005/Marisa#214]
### How to reproduce

1. start a new game with marisa
2. get full charged in battle
3. crash

### Crash log

15:02:08.436 ERROR core.CardCrawlGame> Exception caught
java.lang.ArrayIndexOutOfBoundsException: 2
	at marisa.powers.Marisa.ChargeUpPower.updateDescription(ChargeUpPower.kt:52) ~[MarisaContinued.jar:?]
	at com.megacrit.cardcrawl.actions.common.ApplyPowerAction.update(ApplyPowerAction.java:255) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:179) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:325) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2532) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:876) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [?:?]
Controllers: removed manager for application, 0 managers active
Game crashed.
Version Info:
 - Java version (1.8.0_144)
 - Slay the Spire (12-18-2022)
 - ModTheSpire (3.30.3)
Mod list:
 - basemod (5.52.3)
 - stslib (2.10.0)
 - LazyManKits (1.4.10)
 - Anm2Player (1.3.1)
 - VUPShionMod (7.1.0)
 - actlikeit (1.2.7)
 - Gensokyo (4.0.0)
 - keinemod (0.4.1)
 - MarisaContinued (3.2.0)
 - Library of Ruina (1.1.6)
 - Library of Ruina Extra (1.1.1)
 - intentgraph (0.2.1)
 - ALocalizationUpdate (0.1.0)
 - betterAltar (1.4)
 - Better_Animation (0.2.0)
 - BetterBeginnings (1.4.0)
 - betterLab (1.0)
 - betterMatch (1.1)
 - betterNote (1.3)
 - betterStone (1.1)
 - betterSkull (1.2)
 - betterThird (1.5)
 - betterrewardsmod (4.5.2)
 - neoe_growUp (0.1)
 - loadout (0.9.4)
 - mintyspire (2.5.5)
 - OptimizeTheSpire (1.1.0)
 - neoe_removeCardDiscount (0.1)
 - uncapped (1.1.1)
 - gm-reskin (1.0.1)
 - AKDsMoreRelics (1.4.8)
 - ThisIsPowerMod (1.0.1)
 - StSModEnergizedSpire (1.14.0)

Mods in stacktrace:
 - MarisaContinued (3.2.0)
Cause:
java.lang.ArrayIndexOutOfBoundsException: 2
	at marisa.powers.Marisa.ChargeUpPower.updateDescription(ChargeUpPower.kt:52)
	at com.megacrit.cardcrawl.actions.common.ApplyPowerAction.update(ApplyPowerAction.java:255)
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:179)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:325)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2532)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:876)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by scarf005** [comment]
sorry, i wasn't able to reproduce the issue:

## English
![image](https://github.com/scarf005/Marisa/assets/54838975/96a05da7-dc75-49db-985c-66c045eb7204)

## Simplified chinese
![image](https://github.com/scarf005/Marisa/assets/54838975/c2f8af4f-79a8-40c9-995d-637b7dd8ea06)

## Traditional chinese
![image](https://github.com/scarf005/Marisa/assets/54838975/3187e148-d7fd-4929-b4f8-cd10b05ed942)

could you explain in more detail how the bug happened?

**Comment by scarf005** [comment]
maybe it could be due to namespace collision like in https://github.com/scarf005/Marisa/issues/211#issuecomment-1666441551

**Comment by scarf005** [comment]
could you update to version `v4.0.0` on steam and check if the issue still persists? as this update properly adds namespace to `resources/` directory, it may solve the issue.

related: https://github.com/scarf005/Marisa/releases/tag/v4.0.0

**Comment by URARUA** [comment]
> could you update to version `v4.0.0` on steam and check if the issue still persists? as this update properly adds namespace to `resources/` directory, it may solve the issue.
> 
> related: https://github.com/scarf005/Marisa/releases/tag/v4.0.0

sorry 4 delay, i'll test later

**Comment by URARUA** [comment]
> could you update to version `v4.0.0` on steam and check if the issue still persists? as this update properly adds namespace to `resources/` directory, it may solve the issue.
> 
> related: https://github.com/scarf005/Marisa/releases/tag/v4.0.0

update to v4.0.1 still crashed, i'll disable some mods and try again

```Clearing leaderboard font textures...
12:12:46.863 INFO patches.RunStartEndPatches> Run Started
Shion Flash Power:ChargeUpPower-充-充电时间
Shion Flash Power:ChargeUpPower-充-充电时间
Shion Flash Power:ChargeUpPower-充-充电时间
Shion Flash Power:ChargeUpPower-充-充电时间
Shion Flash Power:ChargeUpPower-充-充电时间
Shion Flash Power:Constricted-缠绕
Shion Flash Power:ChargeUpPower-充-充电时间
Shion Flash Power:GrandCrossPower-增幅
Shion Flash Power:ChargeUpPower-充-充电时间
Shion Flash Power:ChargeUpPower-充-充电时间
12:13:22.605 ERROR core.CardCrawlGame> Exception caught
java.lang.ArrayIndexOutOfBoundsException: 2
	at marisa.powers.Marisa.ChargeUpPower.updateDescription(ChargeUpPower.kt:52) ~[MarisaContinued.jar:?]
	at com.megacrit.cardcrawl.actions.common.ApplyPowerAction.update(ApplyPowerAction.java:255) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:179) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:325) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2532) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:876) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [?:?]
Controllers: removed manager for application, 0 managers active
Game crashed.
Version Info:
 - Java version (1.8.0_144)
 - Slay the Spire (12-18-2022)
 - ModTheSpire (3.30.3)
Mod list:
 - basemod (5.52.3)
 - stslib (2.10.0)
 - LazyManKits (1.4.10)
 - Anm2Player (1.3.1)
 - VUPShionMod (7.1.0)
 - actlikeit (1.2.7)
 - Gensokyo (4.0.0)
 - keinemod (0.4.3)
 - MarisaContinued (4.0.1)
 - Library of Ruina (1.1.6)
 - Library of Ruina Extra (1.1.1)
 - intentgraph (0.2.1)
 - ALocalizationUpdate (0.1.0)
 - betterAltar (1.4)
 - Better_Animation (0.2.0)
 - BetterBeginnings (1.4.0)
 - betterLab (1.0)
 - betterMatch (1.1)
 - betterNote (1.3)
 - betterStone (1.1)
 - betterSkull (1.2)
 - betterThird (1.5)
 - betterrewardsmod (4.5.2)
 - neoe_growUp (0.1)
 - loadout (0.9.4)
 - mintyspire (2.5.5)
 - OptimizeTheSpire (1.1.0)
 - neoe_removeCardDiscount (0.1)
 - gm-reskin (1.0.1)
 - AKDsMoreRelics (1.4.8)
 - ThisIsPowerMod (1.0.1)
 - StSModEnergizedSpire (1.14.0)
 - Koishi514_Mod (1.1.2)
 - Saigyouji_Yuyuko_mod (1.2.1)

Mods in stacktrace:
 - MarisaContinued (4.0.1)
Cause:
java.lang.ArrayIndexOutOfBoundsException: 2
	at marisa.powers.Marisa.ChargeUpPower.updateDescription(ChargeUpPower.kt:52)
	at com.megacrit.cardcrawl.actions.common.ApplyPowerAction.update(ApplyPowerAction.java:255)
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:179)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:325)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2532)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:876)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)```

**Comment by URARUA** [comment]
> sorry, i wasn't able to reproduce the issue:
> 
> ## English
> ![image](https://user-images.githubusercontent.com/54838975/258566254-96a05da7-dc75-49db-985c-66c045eb7204.png)
> 
> ## Simplified chinese
> ![image](https://user-images.githubusercontent.com/54838975/258566750-c2f8af4f-79a8-40c9-995d-637b7dd8ea06.png)
> 
> ## Traditional chinese
> ![image](https://user-images.githubusercontent.com/54838975/258566832-3187e148-d7fd-4929-b4f8-cd10b05ed942.png)
> 
> could you explain in more detail how the bug happened?

hello i found the reason
it got conflicted with [Library of Ruina](https://steamcommunity.com/sharedfiles/filedetails/?id=2405293544)

**Comment by scarf005** [comment]
![image](https://github.com/scarf005/Marisa/assets/54838975/f44b15c6-6a29-42c6-a496-102382bd4e5e)

thanks for the info. the problem is that both marisa and LOR uses same name `ChargeUpPower`, which lead to the mod loading LOR descriptions incorrectly. to fix it, mod id needs to be appended to all translation strings. will try handling it within this week as this is a big change.
