### ISSUE TITLE
Together in spire multiplayer Crash. com.badlogic.gdx.utils.SerializationException: Error parsing file: img/char/Marisa/MarisaModelv3.json

### ISSUE THREAD

**Issue by Legendofshadow** [scarf005/Marisa#222]
### How to reproduce

1. Start Game with Together in spire and Marisa Continued
2. Click Multiplayer.
3. Click Customize.
4. switch to marisa,
5. Crash.

1.Start game with marisa continued and together in spire
2.Start a multiplayer game
3. attempt to scroll to marisa.
4. Crash when it is marisa

### Game language

English (ENG)

### Crash log

Game crashed.
Version Info:
 - Java version (1.8.0_144)
 - Slay the Spire (12-18-2022)
 - ModTheSpire (3.30.3)
Mod list:
 - basemod (5.52.3)
 - stslib (2.10.0)
 - spireTogether (6.0.4)
 - MarisaContinued (4.0.1)

Mods in stacktrace:
 - spireTogether (6.0.4)
Cause:
com.badlogic.gdx.utils.SerializationException: Error parsing file: img/char/Marisa/MarisaModelv3.json
	at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:77)
	at com.esotericsoftware.spine.SkeletonJson.readSkeletonData(SkeletonJson.java:103)
	at spireTogether.monsters.playerChars.NetworkCharPreset.loadAnimation(NetworkCharPreset.java:112)
	at spireTogether.skins.AtlasSkin.LoadSkin(AtlasSkin.java:47)
	at spireTogether.screens.customization.character.CharacterCustomizationScreen.InitializeCharacters(CharacterCustomizationScreen.java:212)
	at spireTogether.screens.customization.character.CharacterCustomizationScreen.GetPreviousCharacter(CharacterCustomizationScreen.java:133)
	at spireTogether.screens.customization.character.CharacterCustomizationScreen.OnLeftArrowClicked(CharacterCustomizationScreen.java:68)
	at spireTogether.screens.customization.AbstractCustomizationDetailsScreen$3.OnLeftClick(AbstractCustomizationDetailsScreen.java:48)
	at spireTogether.ui.elements.useable.Clickable.update(Clickable.java:68)
	at spireTogether.screens.Screen$ElementGroup.update(Screen.java:214)
	at spireTogether.screens.Screen.UpdateIterables(Screen.java:99)
	at spireTogether.screens.Screen.update(Screen.java:81)
	at spireTogether.screens.customization.AbstractCustomizationDetailsScreen.update(AbstractCustomizationDetailsScreen.java:214)
	at spireTogether.screens.customization.character.CharacterCustomizationScreen.update(CharacterCustomizationScreen.java:224)
	at spireTogether.screens.ScreenManager$CustomScreenUpdatePatcher.Insert(ScreenManager.java:121)
	at com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen.update(MainMenuScreen.java:273)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:789)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: img\char\Marisa\MarisaModelv3.json (Internal)
	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:136)
	at com.badlogic.gdx.files.FileHandle.reader(FileHandle.java:163)
	at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:75)
	... 19 more
[SlayTheSpire.log](https://github.com/scarf005/Marisa/files/12270285/SlayTheSpire.log)

**Comment by Legendofshadow** [comment]
i downgraded to 3.2.1 as the last time this worked with together in spire if it helps

**Comment by scarf005** [comment]
thank you for the report. like what you said, I suspect resource path changes in https://github.com/scarf005/Marisa/releases/tag/v4.0.0 caused incompatibility with together in spire. I'll contact them to see if there could be a fix for this.

**Comment by scarf005** [comment]
![image](https://github.com/scarf005/Marisa/assets/54838975/613f1851-854e-4099-9746-0dbc8c0d2e49)

(works in v6.4.11)

![image](https://github.com/scarf005/Marisa/assets/54838975/537e26b4-8f11-4a55-ba0e-6370983743a4)

![image](https://github.com/scarf005/Marisa/assets/54838975/f2b73f49-1724-4d8b-b11b-beb8fe78a397)

hi, sorry for taking so long. i'll close this issue as it's fixed in spireTogether v6.1.0 and v6.1.1.
