### ISSUE TITLE
Crash when Charge Up raises to 8 (from 7)

### ISSUE THREAD

**Issue by Hash56** [scarf005/Marisa#259]
### Mod version

4.0.6

### How to reproduce

Obtain 8 Charge Up

### Game language

English (ENG)

### Crash log

Game crashed.
Version Info:
 - Java version (1.8.0_144)
 - Slay the Spire (12-18-2022)
 - ModTheSpire (3.30.3)
Mod list:
 - basemod (5.54.1)
 - stslib (2.11.0)
 - rngFix (1.0)
 - OptimizeTheSpire (1.1.0)
 - RandomCharacterMod (1.0.1)
 - RandomCharacterButton (1.1.0)
 - coloredmap (2.4.1)
 - coloredpowertips (2.3.0)
 - AchievementEnabler (1.0.0)
 - mintyspire (2.5.8)
 - betterMatch (1.1)
 - betterNote (1.3.1)
 - betterThird (1.5)
 - actlikeit (1.2.8)
 - Abyss (1.3.0)
 - bundlecore (6.2.4)
 - bundle_of_food (4.0.5)
 - bundle_of_potions (3.0.10)
 - downfall (5.2.04)
 - Elementarium (1.10.0)
 - Gensokyo (4.0.0)
 - LimbusCompany (1.0.2)
 - Menagerie (1.6.2)
 - ruina (3.7.0)
 - anniv6 (1.4.7)
 - sagemod (0.5.3)
 - SoulEssences (1.0)
 - HugYouRelics (2.0.6)
 - MarisaContinued (4.0.6)
 - anniv5 (2.3.6)
 - expansionPacks (1.5.2)
 - aspiration (1.9.5)
 - Anm2Player (1.3.4)
 - Hallownest (1.0.2)
 - IsaacMod (1.3.1)
 - IsaacModExtend (1.2.2)
 - MoreIsaacExpansion (1.0.3)
 - Library of Ruina (1.1.6)
 - widepotions (1.3.4)
 - bigcards (1.2.1)
 - spicyShops (1.2.4)
 - CardAugments (1.0.5)
 - chimeracardsplus (0.4.6)
 - mojichimera (0.7.7)

Mods in stacktrace:
 - MarisaContinued (4.0.6)
Cause:
java.lang.ArrayIndexOutOfBoundsException: 2
	at marisa.powers.Marisa.ChargeUpPower.updateDescription(ChargeUpPower.kt:52)
	at com.megacrit.cardcrawl.actions.common.ApplyPowerAction.update(ApplyPowerAction.java:255)
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:179)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:325)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2532)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:876)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by scarf005** [comment]
https://github.com/user-attachments/assets/a3bcf122-3624-4a04-b854-3caf51f859c1

![Image](https://github.com/user-attachments/assets/c02066c6-5011-4e54-8e30-7e56e950e52e)

I was unable to reproduce the issue. maybe some mods with same ID are conflicting each other?

**Comment by scarf005** [comment]
...oh wait, it actually is an duplicate of #214. let's continue there. until a fix is made, please turn off LOR mod for now.
