### ISSUE TITLE
crashes on mod settings

### ISSUE THREAD

**Issue by scarf005** [scarf005/Marisa#65]
[Original post](https://steamcommunity.com/workshop/filedetails/discussion/2902980404/6580353067883192336/)

```
Cause:
java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.lang.String.charAt(String.java:658)
	at com.megacrit.cardcrawl.helpers.FontHelper.identifyColor(FontHelper.java:1218)
	at com.megacrit.cardcrawl.helpers.FontHelper.renderSmartText(FontHelper.java:953)
	at com.evacipated.cardcrawl.modthespire.patches.modsscreen.ModsScreen.renderModInfo(ModsScreen.java:354)
	at com.evacipated.cardcrawl.modthespire.patches.modsscreen.ModsScreen.render(ModsScreen.java:221)
	at com.evacipated.cardcrawl.modthespire.patches.modsscreen.ModsScreenUpdateRender$Render.Postfix(ModsScreenUpdateRender.java:32)
	at com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen.render(MainMenuScreen.java:622)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:435)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

**Comment by scarf005** [comment]
<details>
<summary>regenerated full log</summary>
<pre>
Version Info:
 - Java version (1.8.0_131)
 - Slay the Spire (12-18-2022)
 - ModTheSpire (3.30.0)
Mod list:
 - basemod (5.47.0)
 - MarisaContinued (1.5.1)

Begin patching...
Patching enums...Done.
Finding core patches...
Finding patches...
Patching Overrides...
Injecting patches...Done.
Compiling patched classes...Done.
Busting enums...Done.

Setting isModded = true...Done.

Adding ModTheSpire to version...Done.

Initializing mods...
 - BaseMod
   - basemod.BaseMod
libgdx version 1.9.5
04:02:27.136 INFO basemod.BaseMod> initializeGson
04:02:27.160 INFO basemod.BaseMod> initializeTypeMaps
04:02:27.161 INFO basemod.BaseMod> Registered MonsterStrings
04:02:27.164 INFO basemod.BaseMod> Registered PowerStrings
04:02:27.165 INFO basemod.BaseMod> Registered CardStrings
04:02:27.166 INFO basemod.BaseMod> Registered RelicStrings
04:02:27.167 INFO basemod.BaseMod> Registered EventStrings
04:02:27.168 INFO basemod.BaseMod> Registered PotionStrings
04:02:27.169 INFO basemod.BaseMod> Registered CreditStrings
04:02:27.170 INFO basemod.BaseMod> Registered TutorialStrings
04:02:27.171 INFO basemod.BaseMod> Registered KeywordStrings
04:02:27.172 INFO basemod.BaseMod> Registered ScoreBonusStrings
04:02:27.173 INFO basemod.BaseMod> Registered CharacterStrings
04:02:27.174 INFO basemod.BaseMod> Registered UIStrings
04:02:27.176 INFO basemod.BaseMod> Registered OrbStrings
04:02:27.177 INFO basemod.BaseMod> Registered StanceStrings
04:02:27.178 INFO basemod.BaseMod> Registered RunModStrings
04:02:27.180 INFO basemod.BaseMod> Registered BlightStrings
04:02:27.182 INFO basemod.BaseMod> Registered AchievementStrings
04:02:27.182 INFO basemod.BaseMod> initializePowerMap
04:02:27.552 INFO basemod.BaseMod> initializeUnderscorePowerIDs
04:02:27.569 ERROR basemod.DevConsole> Failed to load dev console history: java.nio.file.NoSuchFileException: /home/scarf/.config/ModTheSpire/BaseMod/console-history.txt
   - 459ms
 - Marisa: Continued (?? ???)
   - marisa.MarisaContinued
04:02:27.684 INFO Marisa> creating the color : MARISA_COLOR
   - 104ms
Done.

Starting game...
04:02:27.687 INFO desktop.DesktopLauncher> time: 1671595347687
04:02:27.687 INFO desktop.DesktopLauncher> version: 2022-12-18
04:02:27.688 INFO desktop.DesktopLauncher> libgdx:  1.9.5
04:02:27.688 INFO desktop.DesktopLauncher> default_locale: en_US
04:02:27.688 INFO desktop.DesktopLauncher> default_charset: US-ASCII
04:02:27.689 INFO desktop.DesktopLauncher> default_encoding: ANSI_X3.4-1968
04:02:27.689 INFO desktop.DesktopLauncher> java_version: 1.8.0_131
04:02:27.689 INFO desktop.DesktopLauncher> os_arch: amd64
04:02:27.689 INFO desktop.DesktopLauncher> os_name: Linux
04:02:27.689 INFO desktop.DesktopLauncher> os_version: 5.15.0-56-generic
04:02:27.691 INFO core.SystemStats> MEMORY STATS:
Free Memory: 231Mb
Max Memory: 6,992Mb
Allocated Memory: 1,146Mb
Unallocated Memory: 5,845Mb
Total Free Memory: 6,077Mb
Used Memory: 914Mb

04:02:27.692 INFO core.SystemStats> DISK STATS:
Total Space: 479,526Mb
Usable Space: 267,114Mb
Free Space: 291,544Mb

04:02:27.695 INFO core.DisplayConfig> Reading info.displayconfig
04:02:27.700 INFO core.DisplayConfig> DisplayConfig successfully read.
04:02:27.700 INFO desktop.DesktopLauncher> [WINDOWED_MODE]
04:02:27.701 INFO desktop.DesktopLauncher> Settings successfully loaded
04:02:27.701 INFO desktop.DesktopLauncher> Launching application...
04:02:28.118 INFO ststwitch.TwitchConfig> The 'twitchconfig.txt' already exists, not overwriting it.
04:02:28.121 INFO core.CardCrawlGame> DistributorPlatform=steam
04:02:28.122 INFO core.CardCrawlGame> isModded=true
04:02:28.122 INFO core.CardCrawlGame> isBeta=false
04:02:28.184 INFO steam.SteamIntegration> [SUCCESS] Steam API initialized successfully.
04:02:28.189 INFO steam.SteamIntegration> BUILD ID: 10180494
04:02:28.190 INFO steam.SteamIntegration> CURRENT LANG: english
04:02:28.191 INFO steam.SteamIntegration> ACCOUNT ID: 208420691
04:02:28.193 INFO steam.SteamIntegration> requestGlobalStats
04:02:28.193 INFO steam.SteamTicker> Steam Ticker initialized.
04:02:28.196 INFO core.CardCrawlGame> No migration
04:02:28.201 INFO core.Settings> Initializing display settings...
04:02:28.202 INFO core.DisplayConfig> Reading info.displayconfig
04:02:28.202 INFO core.DisplayConfig> DisplayConfig successfully read.
04:02:28.203 INFO core.Settings> Initializing sound settings...
04:02:28.204 INFO core.Settings> Initializing game settings...
04:02:28.249 INFO localization.LocalizedStrings> Loc Strings load time: 37ms
04:02:28.250 INFO basemod.BaseMod> begin editing localization strings
04:02:28.253 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.RunModStrings
04:02:28.256 INFO Marisa> start editing strings
04:02:28.258 INFO Marisa> lang : kr
04:02:28.260 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.RelicStrings
04:02:28.261 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.CardStrings
04:02:28.264 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.PowerStrings
04:02:28.265 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.PotionStrings
04:02:28.266 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.EventStrings
04:02:28.268 INFO Marisa> done editing strings
04:02:28.293 INFO audio.MusicMaster> Music Volume: 0.5
04:02:28.299 INFO audio.SoundMaster> Sound Effect Volume: 0.5
04:02:28.300 INFO audio.SoundMaster> Loaded 368 Sound Effects
04:02:28.301 INFO audio.SoundMaster> SFX load time: 3ms
04:02:28.302 INFO basemod.BaseMod> begin adding custom sounds
04:02:28.302 INFO basemod.BaseMod> Added 0 sounds
04:02:28.400 INFO steam.SSCallback> 1Bloop: 646570
04:02:29.274 INFO cards.AbstractCard> Card Image load time: 965ms
04:02:29.276 INFO basemod.BaseMod> editting keywords
04:02:29.276 INFO Marisa> Setting up custom keywords
04:02:29.280 INFO Marisa> Loading keyword : ??
04:02:29.281 INFO Marisa> Loading keyword : ??? ???
04:02:29.281 INFO Marisa> Loading keyword : ???? ??
04:02:29.281 INFO Marisa> Loading keyword : ??
04:02:29.281 INFO Marisa> Loading keyword : ???
04:02:29.281 INFO Marisa> Loading keyword : ??
04:02:29.281 INFO Marisa> Loading keyword : ????
04:02:29.282 INFO Marisa> Loading keyword : ????
04:02:29.282 INFO Marisa> Loading keyword : ??
04:02:29.282 INFO Marisa> Keywords setting finished.
04:02:29.782 INFO helpers.ImageMaster> Texture load time: 497ms
04:02:30.077 INFO helpers.FontHelper> Font load time: 237ms
04:02:30.084 INFO unlock.UnlockTracker> RED UNLOCKS:   0/9
04:02:30.084 INFO unlock.UnlockTracker> GREEN UNLOCKS: 0/9
04:02:30.084 INFO unlock.UnlockTracker> BLUE UNLOCKS: 0/9
04:02:30.084 INFO unlock.UnlockTracker> PURPLE UNLOCKS: 0/9
04:02:30.084 INFO unlock.UnlockTracker> RELIC UNLOCKS: 0/24
04:02:30.142 INFO unlock.UnlockTracker> CARDS SEEN:    19/0
04:02:30.171 INFO unlock.UnlockTracker> RELICS SEEN:   26/0
04:02:30.172 INFO basemod.BaseMod> publish post refresh - refreshing unlocks
04:02:30.172 INFO basemod.BaseMod> begin editing cards
04:02:30.173 INFO Marisa> adding cards for MARISA
04:02:30.671 INFO Marisa> Adding card : ??? ???
04:02:30.672 INFO Marisa> Adding card : ??
04:02:30.672 INFO Marisa> Adding card : ??? ???
04:02:30.673 INFO Marisa> Adding card : ??? ??
04:02:30.673 INFO Marisa> Adding card : ?? ???
04:02:30.673 INFO Marisa> Adding card : ? ???? ???
04:02:30.673 INFO Marisa> Adding card : ???? ?????
04:02:30.673 INFO Marisa> Adding card : ?????? ?
04:02:30.673 INFO Marisa> Adding card : ?? ?? ??
04:02:30.673 INFO Marisa> Adding card : 66C
04:02:30.673 INFO Marisa> Adding card : 6A
04:02:30.674 INFO Marisa> Adding card : ???? ??
04:02:30.674 INFO Marisa> Adding card : ???
04:02:30.674 INFO Marisa> Adding card : ?? ??
04:02:30.674 INFO Marisa> Adding card : ??? ???
04:02:30.674 INFO Marisa> Adding card : ?? ???
04:02:30.674 INFO Marisa> Adding card : ? ????? ?
04:02:30.675 INFO Marisa> Adding card : ???
04:02:30.675 INFO Marisa> Adding card : ???? ??
04:02:30.675 INFO Marisa> Adding card : ??? ???
04:02:30.676 INFO Marisa> Adding card : ??? ???
04:02:30.676 INFO Marisa> Adding card : ???? ???
04:02:30.676 INFO Marisa> Adding card : ???
04:02:30.677 INFO Marisa> Adding card : ?? ????
04:02:30.677 INFO Marisa> Adding card : ???? ??
04:02:30.677 INFO Marisa> Adding card : ?? ?? ??
04:02:30.677 INFO Marisa> Adding card : ???? ??
04:02:30.677 INFO Marisa> Adding card : ? ? ?
04:02:30.678 INFO Marisa> Adding card : ??? ???
04:02:30.678 INFO Marisa> Adding card : ?? ??
04:02:30.678 INFO Marisa> Adding card : ?? ??
04:02:30.678 INFO Marisa> Adding card : ?? ???
04:02:30.678 INFO Marisa> Adding card : ??? ??
04:02:30.678 INFO Marisa> Adding card : ???
04:02:30.679 INFO Marisa> Adding card : ????
04:02:30.679 INFO Marisa> Adding card : ??!
04:02:30.679 INFO Marisa> Adding card : ?? ??
04:02:30.679 INFO Marisa> Adding card : ??? ??
04:02:30.680 INFO Marisa> Adding card : ??? ??
04:02:30.680 INFO Marisa> Adding card : ?? ?? ??
04:02:30.680 INFO Marisa> Adding card : ????? ???
04:02:30.680 INFO Marisa> Adding card : ?? ???
04:02:30.680 INFO Marisa> Adding card : ??
04:02:30.681 INFO Marisa> Adding card : ????? ??
04:02:30.681 INFO Marisa> Adding card : ???? ???
04:02:30.681 INFO Marisa> Adding card : ?? ??!
04:02:30.681 INFO Marisa> Adding card : ?? ??
04:02:30.682 INFO Marisa> Adding card : ?? ??
04:02:30.682 INFO Marisa> Adding card : ??? ??
04:02:30.682 INFO Marisa> Adding card : ?? ??
04:02:30.682 INFO Marisa> Adding card : ??? ??? ??
04:02:30.682 INFO Marisa> Adding card : ???? ?? ??
04:02:30.682 INFO Marisa> Adding card : ?? ???
04:02:30.683 INFO Marisa> Adding card : ?? ?????
04:02:30.683 INFO Marisa> Adding card : ?? ??
04:02:30.683 INFO Marisa> Adding card : ??
04:02:30.683 INFO Marisa> Adding card : ???
04:02:30.683 INFO Marisa> Adding card : ?? ??
04:02:30.683 INFO Marisa> Adding card : ????? ???
04:02:30.683 INFO Marisa> Adding card : ?? ??
04:02:30.684 INFO Marisa> Adding card : ??? ?????
04:02:30.684 INFO Marisa> Adding card : ?? ??
04:02:30.684 INFO Marisa> Adding card : ??
04:02:30.684 INFO Marisa> Adding card : ??
04:02:30.684 INFO Marisa> Adding card : ???? ??
04:02:30.684 INFO Marisa> Adding card : ????? ???
04:02:30.684 INFO Marisa> Adding card : ??? ??
04:02:30.685 INFO Marisa> Adding card : ???? ?
04:02:30.685 INFO Marisa> Adding card : ???? ??
04:02:30.685 INFO Marisa> Adding card : ??? ???
04:02:30.685 INFO Marisa> Adding card : ???
04:02:30.685 INFO Marisa> Adding card : ?? ?? ??
04:02:30.685 INFO Marisa> Adding card : ?? ??
04:02:30.685 INFO Marisa> Adding card : ??? ??
04:02:30.686 INFO Marisa> Adding card : ???
04:02:30.686 INFO Marisa> Adding card : ???
04:02:30.686 INFO Marisa> Adding card : ???
04:02:30.686 INFO Marisa> Adding card : ????
04:02:30.686 INFO Marisa> Adding card : ????
04:02:30.686 INFO Marisa> Adding card : ??
04:02:30.687 INFO Marisa> Adding card : ??
04:02:30.687 INFO Marisa> done editing cards
04:02:30.769 INFO panels.TopPanel> Twitch Integration enabled due to presence of 'twitch.properties` file.
04:02:30.769 INFO panels.TopPanel> Not starting twitch integration because enabled=false
04:02:30.794 INFO core.DisplayConfig> Reading info.displayconfig
04:02:30.795 INFO core.DisplayConfig> DisplayConfig successfully read.
04:02:31.009 INFO helpers.CardLibrary> Card load time: 322ms with 451 cards
04:02:31.009 INFO basemod.BaseMod> begin editing relics
04:02:31.010 INFO Marisa> Begin editing relics.
04:02:31.013 INFO helpers.ImageMaster> [WARNING] No image at images/relics/
04:02:31.014 INFO helpers.ImageMaster> [WARNING] No image at images/relics/outline/
04:02:31.020 INFO helpers.ImageMaster> [WARNING] No image at images/relics/
04:02:31.020 INFO helpers.ImageMaster> [WARNING] No image at images/relics/outline/
04:02:31.023 INFO helpers.ImageMaster> [WARNING] No image at images/relics/
04:02:31.024 INFO helpers.ImageMaster> [WARNING] No image at images/relics/outline/
04:02:31.026 INFO helpers.ImageMaster> [WARNING] No image at images/relics/
04:02:31.026 INFO helpers.ImageMaster> [WARNING] No image at images/relics/outline/
04:02:31.029 INFO helpers.ImageMaster> [WARNING] No image at images/relics/
04:02:31.030 INFO helpers.ImageMaster> [WARNING] No image at images/relics/outline/
04:02:31.032 INFO helpers.ImageMaster> [WARNING] No image at images/relics/
04:02:31.033 INFO helpers.ImageMaster> [WARNING] No image at images/relics/outline/
04:02:31.036 INFO helpers.ImageMaster> [WARNING] No image at images/relics/
04:02:31.036 INFO helpers.ImageMaster> [WARNING] No image at images/relics/outline/
04:02:31.038 INFO helpers.ImageMaster> [WARNING] No image at images/relics/
04:02:31.039 INFO helpers.ImageMaster> [WARNING] No image at images/relics/outline/
04:02:31.041 INFO helpers.ImageMaster> [WARNING] No image at images/relics/
04:02:31.041 INFO helpers.ImageMaster> [WARNING] No image at images/relics/outline/
04:02:31.043 INFO helpers.ImageMaster> [WARNING] No image at images/relics/
04:02:31.044 INFO helpers.ImageMaster> [WARNING] No image at images/relics/outline/
04:02:31.046 INFO helpers.ImageMaster> [WARNING] No image at images/relics/
04:02:31.046 INFO helpers.ImageMaster> [WARNING] No image at images/relics/outline/
04:02:31.049 INFO helpers.ImageMaster> [WARNING] No image at images/relics/
04:02:31.049 INFO helpers.ImageMaster> [WARNING] No image at images/relics/outline/
04:02:31.052 INFO helpers.ImageMaster> [WARNING] No image at images/relics/
04:02:31.052 INFO helpers.ImageMaster> [WARNING] No image at images/relics/outline/
04:02:31.053 INFO Marisa> Relics editing finished.
04:02:31.183 INFO helpers.RelicLibrary> Relic load time: 130ms
04:02:31.184 INFO input.InputHelper> Setting input processor to Scroller
04:02:31.203 INFO steamInput.SteamInputHelper> Starting input detection...
04:02:31.209 INFO integrations.SteelSeries> enabled=false
04:02:31.217 INFO basemod.BaseMod> postCreateStartingRelics for: IRONCLAD
04:02:31.217 INFO basemod.BaseMod> postCreateStartingRelics adding [ Burning Blood ]
04:02:31.302 INFO basemod.BaseMod> postCreateStartingRelics for: THE_SILENT
04:02:31.302 INFO basemod.BaseMod> postCreateStartingRelics adding [ Ring of the Snake ]
04:02:31.329 INFO basemod.BaseMod> postCreateStartingRelics for: DEFECT
04:02:31.329 INFO basemod.BaseMod> postCreateStartingRelics adding [ Cracked Core ]
04:02:31.358 INFO basemod.BaseMod> postCreateStartingRelics for: WATCHER
04:02:31.358 INFO basemod.BaseMod> postCreateStartingRelics adding [ PureWater ]
04:02:31.389 INFO basemod.BaseMod> begin editing characters
04:02:31.389 INFO Marisa> begin editing characters
04:02:31.389 INFO Marisa> add MARISA
04:02:31.398 INFO basemod.BaseMod> postCreateStartingRelics for: MARISA
04:02:31.398 INFO basemod.BaseMod> postCreateStartingRelics adding [ MiniHakkero ]
04:02:31.400 INFO marisa.MarisaContinued> init Marisa
04:02:31.482 INFO marisa.MarisaContinued> init finish
04:02:31.482 INFO Marisa> done editing characters
04:02:31.486 INFO basemod.BaseMod> publishPostInitialize
04:02:31.514 INFO basemod.BaseMod> registerModBadge : BaseMod
04:02:31.515 INFO basemod.ModBadge> initialized mod badge for: BaseMod
04:02:31.515 INFO basemod.ModBadge> setup hooks for BaseMod mod badge
04:02:31.519 INFO basemod.BaseMod> initializeUnderscoreCardIDs
04:02:31.519 INFO basemod.BaseMod> initializeUnderscorePotionIDs
04:02:31.520 INFO basemod.BaseMod> initializeUnderscoreEventIDs
04:02:31.520 INFO basemod.BaseMod> initializeUnderscoreRelicIDs
04:02:31.520 INFO basemod.BaseMod> initializeEncounters
04:02:31.543 INFO Marisa> Adding badge, configs,event and potion
04:02:31.560 INFO EventUtil> Event Mushrooms_MRS registered. ANY | [Exordium]
04:02:31.561 INFO EventUtil> Event OrinTheCat registered. ANY | [TheBeyond]
04:02:31.562 INFO dungeons.AbstractDungeon> Generating seeds: 0
04:02:31.606 INFO basemod.BaseMod> registerModBadge : MarisaContinued
04:02:31.606 INFO basemod.ModBadge> initialized mod badge for: MarisaContinued
04:02:31.606 INFO basemod.ModBadge> setup hooks for MarisaContinued mod badge
04:02:33.942 INFO stats.StatsScreen> Loading character stats.
04:02:33.944 INFO steam.SteamIntegration> unlockAchievement: COME_AT_ME
04:02:33.945 INFO steam.SteamIntegration> unlockAchievement: THE_PACT
04:02:33.946 INFO steam.SteamIntegration> unlockAchievement: ADRENALINE
04:02:33.946 INFO steam.SteamIntegration> unlockAchievement: POWERFUL
04:02:34.006 INFO steam.SSCallback> Stat Stored
04:02:34.006 INFO basemod.BaseMod> publishAddCustomModeMods
04:02:34.006 INFO steam.SSCallback> Stat Stored
04:02:34.007 INFO steam.SSCallback> Stat Stored
04:02:34.007 INFO steam.SSCallback> Stat Stored
04:02:34.012 INFO core.DisplayConfig> Reading info.displayconfig
04:02:34.013 INFO core.DisplayConfig> DisplayConfig successfully read.
04:02:34.223 INFO unlock.UnlockTracker> RED UNLOCKS:   0/9
04:02:34.223 INFO unlock.UnlockTracker> GREEN UNLOCKS: 0/9
04:02:34.223 INFO unlock.UnlockTracker> BLUE UNLOCKS: 0/9
04:02:34.223 INFO unlock.UnlockTracker> PURPLE UNLOCKS: 0/9
04:02:34.223 INFO unlock.UnlockTracker> RELIC UNLOCKS: 0/24
04:02:34.224 INFO unlock.UnlockTracker> CARDS SEEN:    19/451
04:02:34.224 INFO unlock.UnlockTracker> RELICS SEEN:   26/179
04:02:34.224 INFO UnlockTracker.CountModdedUnlockCards> Counting modded unlocks.
04:02:34.224 INFO UnlockTracker.CountModdedUnlockCards> MARISA UNLOCKS:	0/0
04:02:34.225 INFO basemod.BaseMod> publish post refresh - refreshing unlocks
04:02:34.225 INFO UnlockTracker.CountModdedUnlockCards> Counting modded unlocks.
04:02:34.225 INFO UnlockTracker.CountModdedUnlockCards> MARISA UNLOCKS:	0/0
04:02:34.225 INFO compendium.CardLibraryScreen> Initializing card library screen.
04:02:34.236 INFO basemod.BaseMod> postCreateStartingRelics for: IRONCLAD
04:02:34.237 INFO basemod.BaseMod> postCreateStartingRelics adding [ Burning Blood ]
04:02:34.275 INFO characters.CharacterManager> Successfully recreated IRONCLAD
04:02:34.276 INFO basemod.BaseMod> postCreateStartingRelics for: THE_SILENT
04:02:34.276 INFO basemod.BaseMod> postCreateStartingRelics adding [ Ring of the Snake ]
04:02:34.306 INFO characters.CharacterManager> Successfully recreated THE_SILENT
04:02:34.306 INFO basemod.BaseMod> postCreateStartingRelics for: DEFECT
04:02:34.306 INFO basemod.BaseMod> postCreateStartingRelics adding [ Cracked Core ]
04:02:34.339 INFO characters.CharacterManager> Successfully recreated DEFECT
04:02:34.340 INFO basemod.BaseMod> postCreateStartingRelics for: WATCHER
04:02:34.340 INFO basemod.BaseMod> postCreateStartingRelics adding [ PureWater ]
04:02:34.376 INFO characters.CharacterManager> Successfully recreated WATCHER
04:02:34.384 INFO basemod.BaseMod> postCreateStartingRelics for: MARISA
04:02:34.384 INFO basemod.BaseMod> postCreateStartingRelics adding [ MiniHakkero ]
04:02:34.386 INFO marisa.MarisaContinued> init Marisa
04:02:34.505 INFO marisa.MarisaContinued> init finish
04:02:34.505 INFO characters.CharacterManager> Successfully recreated MARISA
04:02:34.591 INFO saveAndContinue.SaveAndContinue> IRONCLAD save does NOT exist!
04:02:34.592 INFO saveAndContinue.SaveAndContinue> THE_SILENT save does NOT exist!
04:02:34.592 INFO saveAndContinue.SaveAndContinue> DEFECT save does NOT exist!
04:02:34.592 INFO saveAndContinue.SaveAndContinue> WATCHER save does NOT exist!
04:02:34.613 INFO saveAndContinue.SaveAndContinue> saves/1_MARISA.autosave save file was successfully loaded.
04:02:34.614 INFO saveAndContinue.SaveAndContinue> MARISA save exists and is valid.
04:02:36.705 INFO steamInput.SteamInputDetect> Steam input detect thread interrupted!
04:02:36.706 INFO steamInput.SteamInputDetect> Steam input detect thread will die now.
04:02:36.716 INFO controller.CInputHelper> [CONTROLLER] Utilizing DirectInput
Controllers: added manager for application, 1 managers active
04:02:36.727 INFO controller.CInputHelper> [CONTROLLER] No controllers detected
04:02:41.748 INFO core.CardCrawlGame> Exception occurred in CardCrawlGame render method!
04:02:41.750 ERROR core.CardCrawlGame> Exception caught
java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.lang.String.charAt(String.java:658) ~[?:1.8.0_131]
	at com.megacrit.cardcrawl.helpers.FontHelper.identifyColor(FontHelper.java:1218) ~[?:?]
	at com.megacrit.cardcrawl.helpers.FontHelper.renderSmartText(FontHelper.java:953) ~[?:?]
	at com.evacipated.cardcrawl.modthespire.patches.modsscreen.ModsScreen.renderModInfo(ModsScreen.java:354) ~[?:?]
	at com.evacipated.cardcrawl.modthespire.patches.modsscreen.ModsScreen.render(ModsScreen.java:221) ~[?:?]
	at com.evacipated.cardcrawl.modthespire.patches.modsscreen.ModsScreenUpdateRender$Render.Postfix(ModsScreenUpdateRender.java:32) ~[?:?]
	at com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen.render(MainMenuScreen.java:622) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:435) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [?:?]
Controllers: removed manager for application, 0 managers active
04:02:41.758 INFO core.CardCrawlGame> PAUSE()
04:02:41.758 INFO core.CardCrawlGame> Game shutting down...
04:02:41.758 INFO core.CardCrawlGame> Flushing saves to disk...
04:02:41.760 INFO core.CardCrawlGame> Shutting down controller handler...
04:02:41.760 INFO core.CardCrawlGame> Shutting down publisher integrations...
04:02:41.765 INFO core.CardCrawlGame> Flushing logs to disk. Clean shutdown successful.

Game crashed.
Version Info:
 - Java version (1.8.0_131)
 - Slay the Spire (12-18-2022)
 - ModTheSpire (3.30.0)
Mod list:
 - basemod (5.47.0)
 - MarisaContinued (1.5.1)

Cause:
java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.lang.String.charAt(String.java:658)
	at com.megacrit.cardcrawl.helpers.FontHelper.identifyColor(FontHelper.java:1218)
	at com.megacrit.cardcrawl.helpers.FontHelper.renderSmartText(FontHelper.java:953)
	at com.evacipated.cardcrawl.modthespire.patches.modsscreen.ModsScreen.renderModInfo(ModsScreen.java:354)
	at com.evacipated.cardcrawl.modthespire.patches.modsscreen.ModsScreen.render(ModsScreen.java:221)
	at com.evacipated.cardcrawl.modthespire.patches.modsscreen.ModsScreenUpdateRender$Render.Postfix(ModsScreenUpdateRender.java:32)
	at com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen.render(MainMenuScreen.java:622)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:435)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
</pre>
</details>

**Comment by scarf005** [comment]
cause found: `#` in description is used as rgb modifier, and crashed the game
```json
{
  "modid": "MarisaContinued",
  "name": "Marisa: Continued (霧雨 魔理沙)",
  "description": "Adds Marisa (霧雨 魔理沙) from Touhou Project as a new playable character.\n\n# v1.5.1 (2022-12-21)\n\n## New Features\n\n- make `acceleration` shuffle empty deck (#63)\n\n## Fixes\n\n- shoot the moon removing transient's debuffs (#59)\n",
  "version": "1.5.1\n",
  "sts_version": "12-01-2022",
  "mts_version": "3.30.0",
  "author_list": [
    "Flynn",
    "Hell",
    "Hohner257",
    "Samsara",
    "scarf005"
  ],
  "credits": "Original mod: https://steamcommunity.com/sharedfiles/filedetails/?id=1614104912",
  "dependencies": [
    "basemod"
  ]
}
```
